// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Overgear.Models;

namespace Overgear.Migrations
{
    [DbContext(typeof(OvergearContext))]
    [Migration("20180923164012_AppointmentMigration")]
    partial class AppointmentMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("Overgear.Models.Appointment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("allDay");

                    b.Property<string>("end");

                    b.Property<string>("start");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("Overgear.Models.Boot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("Quantity")
                        .IsRequired();

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Boot");
                });

            modelBuilder.Entity("Overgear.Models.Gloves", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("Quantity")
                        .IsRequired();

                    b.Property<string>("Size");

                    b.HasKey("ID");

                    b.ToTable("Gloves");
                });

            modelBuilder.Entity("Overgear.Models.Headgear", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("Quantity")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Headgear");
                });

            modelBuilder.Entity("Overgear.Models.HighVisibility", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("Quantity")
                        .IsRequired();

                    b.Property<string>("Size")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("HighVisibility");
                });

            modelBuilder.Entity("Overgear.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Quantity");

                    b.Property<int?>("RequestID");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.HasIndex("RequestID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Overgear.Models.Outerwear", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("Quantity")
                        .IsRequired();

                    b.Property<string>("Size")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Outerwear");
                });

            modelBuilder.Entity("Overgear.Models.Pants", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("Quantity")
                        .IsRequired();

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Pants");
                });

            modelBuilder.Entity("Overgear.Models.Request", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("Overgear.Models.Shirt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("Quantity")
                        .IsRequired();

                    b.Property<string>("Size")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Shirt");
                });

            modelBuilder.Entity("Overgear.Models.Shoe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("Quantity")
                        .IsRequired();

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Shoe");
                });

            modelBuilder.Entity("Overgear.Models.Item", b =>
                {
                    b.HasOne("Overgear.Models.Request")
                        .WithMany("Items")
                        .HasForeignKey("RequestID");
                });
#pragma warning restore 612, 618
        }
    }
}
