// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Overgear.Models;

namespace Overgear.Migrations
{
    [DbContext(typeof(OvergearContext))]
    [Migration("20180923003710_SqlLiteMigrations")]
    partial class SqlLiteMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("Overgear.Models.Boot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour");

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Boot");
                });

            modelBuilder.Entity("Overgear.Models.Gloves", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Gloves");
                });

            modelBuilder.Entity("Overgear.Models.Headgear", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour");

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Headgear");
                });

            modelBuilder.Entity("Overgear.Models.HighVisibility", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("HighVisibility");
                });

            modelBuilder.Entity("Overgear.Models.Outerwear", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour");

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Outerwear");
                });

            modelBuilder.Entity("Overgear.Models.Pants", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour");

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Pants");
                });

            modelBuilder.Entity("Overgear.Models.Shirt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour");

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Shirt");
                });

            modelBuilder.Entity("Overgear.Models.Shoe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Shoe");
                });
#pragma warning restore 612, 618
        }
    }
}
