// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Overgear.Models;

namespace Overgear.Migrations
{
    [DbContext(typeof(OvergearContext))]
    partial class OvergearContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Overgear.Models.Boot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Colour");

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Boot");
                });

            modelBuilder.Entity("Overgear.Models.Gloves", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Gloves");
                });

            modelBuilder.Entity("Overgear.Models.Headgear", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Colour");

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Headgear");
                });

            modelBuilder.Entity("Overgear.Models.HighVisibility", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("HighVisibility");
                });

            modelBuilder.Entity("Overgear.Models.Outerwear", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Colour");

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Outerwear");
                });

            modelBuilder.Entity("Overgear.Models.Pants", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Colour");

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Pants");
                });

            modelBuilder.Entity("Overgear.Models.Shirt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Colour");

                    b.Property<string>("Description");

                    b.Property<int>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("ID");

                    b.ToTable("Shirt");
                });
#pragma warning restore 612, 618
        }
    }
}
